algoritmo "ConversorMoedas"
// Função :
// Autor : Heitor Berg
// Data : 18/09/2024
// Seção de Declarações 
var
 D, R, Re:Real
inicio
      Escreval ("--------------------")
      Escreval ("Conversor de Moedas")
      Escreval ("--------------------")
      Escreva ("Qual o Valor Em R$?")
      Leia (R)
      Escreva ("Qual o Valor do Dolar No momento?")
      Leia (D)
      Re <- R/D
      Escreva ("O Valor Convertido Sera ", Re, " Dolar(es)")

fimalgoritmo
